### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by TDL77** [smeyanoff/dvc-example#1]
Выложите пожалуйста файл .env 
пытаюсь воспроизвести и пока ошибка на ошибке идет

.env
prepare_stage1:
INITIAL_DATA_PATH=./data/initial_data/ poetry run python src/data/data_download.py

prepare_stage2:
INITIAL_DATA_PATH=./data/initial_data/ 
PREPARED_DATA_PATH=./data/prepared_data/ poetry run python src/data/data_prepare.py

training:
INITIAL_DATA_PATH=./data/initial_data/ 
PREPARED_DATA_PATH=./data/prepared_data/ 
MODELS_PATH=./models/ poetry run python src/models/model_train.py

data_prepare: prepare_stage1 prepare_stage2 training

**Comment by smeyanoff** [comment]
Добрый день
Выложил
